volumes:
  library_frontend_db:

services:
  library_frontend_server:
    env_file:
      - .env
    restart: on-failure
    build:
      context: .
    image: library_frontend:latest
    entrypoint: [ "/start_docker.sh" ]
    command: gunicorn -b 0.0.0.0:8000 --worker-class=gevent --worker-connections=1000 --workers=2 main.wsgi
    ports:
      - '2001:8000'
    volumes:
      - .:/code
    depends_on:
      - library_frontend_db

  library_frontend_db:
    image: postgres:16-bookworm
    container_name: library_frontend_db
    environment:
      - POSTGRES_USER=frontend_user
      - POSTGRES_PASSWORD=frontend_password
      - POSTGRES_DB=library_frontend_db
    ports:
        - "7433:5432"
    volumes:
        - library_frontend_db:/var/lib/postgresql/data

