# Generated by Django 5.1.1 on 2025-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendbook',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
